### ISSUE TITLE
Not rendering in storyboards

### ISSUE THREAD

**Issue by waltermvp** [mchoe/SwiftSVG#13]
Just subclassed a regular UIView to inherit from SVGView and set the svg name but it does not render. Im using the latest version of xcode and have introduced the framework via cocoapods. am i missing something? All i get is a blank view. 

I go det "Designables Error" in the storyboard inspector

**Comment by mchoe** [comment]
Hi @waltermvp, I just tested this on a fresh project and everything seems to be working ok.

A couple things that come to mind: 1) You want to make sure that the Module under the SVGView class in Interface Builder is using the SwiftSVG module; and 2) Make sure you export your SVG to be cropped so that there is no space around it. It may be rendering it out of the clipped bounds of the view.

I'm going to close this issue, but feel free to ask any troubleshooting questions here.

**Comment by waltermvp** [comment]
@mchoe thank you for the quick response much appreciated, and even more thanks for this awesome lib
