### ISSUE TITLE
SwiftSVG render one file with incorrect orientation 

### ISSUE THREAD

**Issue by alexanderkhitev** [mchoe/SwiftSVG#145]
SwiftSVG renders one file with incorrect orientation. For example, this file has been displayed as inverted. You can check this in Google Chrome
[TestMask.svg.zip](https://github.com/mchoe/SwiftSVG/files/3534111/TestMask.svg.zip)

**Comment by mchoe** [comment]
Looks like the sample SVG uses the `<use>` tag where the fill and transforms are applied. Unfortunately, the library doesn't support that tag at this time which is why the SVG isn't rendered properly. If you have control over the SVG, you can replace the `<use>` tag with a `<path>` tag and cut and paste the path data into the `<path>` tag.
