### ISSUE TITLE
A decimal without a leading zero can follow another decimal without whitespace

### ISSUE THREAD

**Issue by pwesten** [mchoe/SwiftSVG#43]
In other words, the text "35.5.8" should be interpreted (greedily) as "35.5 0.8". Reproduced against feature/2.0.0 branch.

**Comment by mchoe** [comment]
Hi @pwesten. Unfortunately, this isn't supported because of the way numbers in paths are parsed. I'm considering switching to using regex to parse path numbers in the future, but I wanted keep the parsing simple to understand, so decided to stick with a number stack for now instead.

I'm curious to hear what app you're using to output your SVGs so I can see whether it's something I should consider sooner rather than later. Thanks.

**Comment by pwesten** [comment]
Hi @mchoe thanks for the response; my designer was producing SVGs in Illustrator, which as I understand it has some export controls for minimizing the resulting file. My assumption is that it's simple trying to eliminate all whitespace that isn't strictly necessary.

**Comment by mchoe** [comment]
I see, thanks for the info. The SVG specification itself doesn't support greedily interpreted numbers as I see it:

<img width="469" alt="screen shot 2017-09-01 at 11 34 57 am" src="https://user-images.githubusercontent.com/2816885/29976938-c140f9dc-8f09-11e7-98de-9f6380ad6047.png">

However, seeing the file is from Illustrator, I will look into it to see what's going on. Thanks.
